version: '3.8'

services:
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  web:
    build: .
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY=dev-secret-key
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A tasks.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis
